language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - "lts/*"
script:
  - npm run test:prod && npm run build && ./tools/e2e.sh
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
